fiddling with pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -27,6 +27,7 @@ variables:
   GOPATH: '/tmp/go'
   GOBIN:  '$(GOPATH)/bin'
   repository: 'focal-freedom-236620/operator'
+  USE_GKE_GCLOUD_AUTH_PLUGIN: 'True'
   build: $(Build.BuildId)
   ref: $(Build.SourceBranch)
   branch: $(Build.SourceBranchName)
@@ -35,16 +36,73 @@ variables:
 jobs:
 - job: Operator
   pool:
-    vmImage: 'Ubuntu-18.04'
+    vmImage: 'Ubuntu-20.04'
 
   steps:
   - script: |
+      echo 'test1'
       set -e
       mkdir -p '$(GOBIN)'
       mkdir -p '$(GOPATH)/pkg'
       echo '##vso[task.prependpath]$(GOBIN)'
       echo '##vso[task.prependpath]$(GOROOT)/bin'
     displayName: 'Set up the Go workspace'
+
+
+  - task: KubectlInstaller@0
+    displayName: Kubectl installer
+    inputs:
+      kubectlVersion: 1.25.2
+
+  - script: |
+      set -e
+      sudo make kustomize
+    displayName: 'Install kustomize'
+
+  - task: DownloadSecureFile@1
+    displayName: 'Download secure file'
+    inputs:
+      secureFile: 'azure-gcp.json'
+
+  - bash: |
+      set -e
+      keyFilePath="$(Agent.TempDirectory)/azure-gcp.json"
+      gcloud components list
+      
+      echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+      
+      curl -f https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
+
+      sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
+      
+      gke-gcloud-auth-plugin --version
+      
+      # echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" > ~/.bashrc
+      # source ~/.bashrc
+      
+      
+      
+      gcloud --quiet auth activate-service-account --key-file="${keyFilePath}"
+      gcloud --quiet config set project $(gcp.project.name)
+      gcloud --quiet container clusters get-credentials $(gcp.cluster.name) --region $(gcp.cluster.region)
+      
+
+      echo "Trying namespaces"
+      kubectl get namespaces
+
+    displayName: 'Connect to cluster'
+
+
+  - bash: |
+      set -e
+      
+      kubectl config get-contexts
+      
+      echo "Trying namespaces"
+      kubectl get namespaces
+    displayName: 'kubectl: Trying contexts'
+
+
 
   - task: GoTool@0
     inputs:
@@ -60,6 +118,11 @@ jobs:
       fi
       echo "##vso[task.setvariable variable=version]$VERS"
     displayName: 'Set version variable'
+
+
+
+
+
 
   - script: |
       set -e
@@ -80,39 +143,18 @@ jobs:
         $(branch)-$(build)
         latest
 
-  - script: |
-      set -e
-      sudo make kubectl
-    displayName: 'Install kubectl'
-
+##  - script: |
+##      set -e
+##      sudo make kubectl
+##    displayName: 'Install kubectl'
+#
+#
+#
   - script: |
       set -e
       sudo make bats
     displayName: 'Install bats'
 
-  - script: |
-      set -e
-      sudo make kustomize
-    displayName: 'Install kustomize'
-
-  - task: DownloadSecureFile@1
-    displayName: 'Download secure file'
-    inputs:
-      secureFile: 'azure-gcp.json'
-
-  - bash: |
-      set -e
-      keyFilePath="$(Agent.TempDirectory)/azure-gcp.json"
-      if [[ -z $(which gcloud) ]]; then
-        CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
-        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
-        sudo apt-get update && sudo apt-get install -y google-cloud-sdk
-      fi
-      gcloud --quiet auth activate-service-account --key-file="${keyFilePath}"
-      gcloud --quiet config set project $(gcp.project.name)
-      gcloud --quiet container clusters get-credentials $(gcp.cluster.name) --region $(gcp.cluster.region)
-    displayName: 'Connect to cluster'
 
   - script: |
       set -e
@@ -132,11 +174,11 @@ jobs:
       make feature
     displayName: 'Feature tests'
 
-  - script: |
-      set -e
-      kubectl delete ns $(jobuuid)
-    displayName: 'Cleanup tests'
-    condition: failed()
+#  - script: |
+#      set -e
+#      kubectl delete ns $(jobuuid)
+#    displayName: 'Cleanup tests'
+#    condition: failed()
 
   - script: |
       set -e
